///////////////////////////////////////////////////////////
//  SimpleDataTypesList.cs
//  Implementation of the Class SimpleDataTypesList
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:12
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using AutosarGuiEditor.Source.Interfaces;



namespace System {
    public class SimpleDataTypesList : IGuidList<SimpleDataType>
    {
        public override String GetName()
        {
            return "Simple data types";
        }
	}
}