///////////////////////////////////////////////////////////
//  ServerPortPainter.cs
//  Implementation of the Class ServerPortPainter
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:09
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Media.Imaging;
using System.Windows.Media;
using AutosarGuiEditor.Source.AutosarInterfaces;
using AutosarGuiEditor.Source.Interfaces;

namespace AutosarGuiEditor.Source.Painters.PortsPainters 
{
    public static class EmptyPort
    {
        public static void RenderEntrails(RenderContext context, RectanglePainter rectangle)
        {
            context.DrawFillRectangle(rectangle.TopLeft.X + 3, rectangle.TopLeft.Y + 3, rectangle.BottomRight.X - 3, rectangle.BottomRight.Y - 3, Colors.Red);
            context.DrawFillRectangle(rectangle.TopLeft.X + 4, rectangle.TopLeft.Y + 4, rectangle.BottomRight.X - 4, rectangle.BottomRight.Y - 4, Colors.Red);
		}       
	}
}