///////////////////////////////////////////////////////////
//  ComponentPainter.cs
//  Implementation of the Class ComponentPainter
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:10
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using System.Windows.Media;
using System.Windows;
using AutosarGuiEditor.Source.Utility;
using AutosarGuiEditor.Source.Render;
using System.Windows.Media.Imaging;
using AutosarGuiEditor.Source.SystemInterfaces;
using AutosarGuiEditor.Source.Painters.PortsPainters;
using AutosarGuiEditor.Source.Painters.Components.Runables;
using AutosarGuiEditor.Source.Component;
using AutosarGuiEditor.Source.PortDefenitions;
using AutosarGuiEditor.Source.Painters.Components.PerInstance;
using AutosarGuiEditor.Source.Component.PerInstanceMemory;
using AutosarGuiEditor.Source.Fabrics;
using AutosarGuiEditor.Source.Painters.Components.CData;
using AutosarGuiEditor.Source.Component.CData;


namespace AutosarGuiEditor.Source.Painters
{
    public class ComponentInstance : IElementWithPorts
    {
        public RunnableInstancesList RunableInstances = new RunnableInstancesList();
        public PimInstancesList PerInstanceMemories = new PimInstancesList();
        public CDataInstancesList CDataInstances = new CDataInstancesList();

        public ComponentDefenition ComponentDefenition
        {
            get
            {
                return AutosarApplication.GetInstance().ComponentDefenitionsList.FindObject(this.ComponentDefenitionGuid);
            }
        }

        Guid componentDefenitionGuid;
        public Guid ComponentDefenitionGuid
        {
            set
            {
                componentDefenitionGuid = value;
            }
            get
            {
                return componentDefenitionGuid;
            }
        }

        public ComponentInstance()
        {
           
        }

        public override void Render(RenderContext context)
        {
            base.Render(context);

            /* Draw component name*/
            GlyphFont glyphFont = LetterGlyphTool.GetFont(AutosarApplication.GetInstance().ComponentNameFont);
            int width = glyphFont.GetTextWidth(Name);
            int textHeight = glyphFont.GetTextHeight(Name);

            Point textCoord = Painter.Center;
            textCoord.Y = Painter.Top;
            textCoord = context.GetImageCoordinate(textCoord);
            textCoord.Y += textHeight;
            textCoord.X -= (double)width / 2.0d;
            context.Bitmap.DrawString((int)textCoord.X, (int)textCoord.Y, Colors.Black, AutosarApplication.GetInstance().ComponentNameFont, Name);

            String defName = "<" + this.ComponentDefenition.Name + ">";
            glyphFont = LetterGlyphTool.GetFont(AutosarApplication.GetInstance().ComponentDefinitionNameFont);
            width = glyphFont.GetTextWidth(defName);

            textCoord = Painter.Center;
            textCoord.Y = Painter.Top;
            textCoord = context.GetImageCoordinate(textCoord);
            textCoord.X -= (double)width / 2.0d;
            
            context.Bitmap.DrawString((int)textCoord.X, (int)textCoord.Y, Colors.Black, AutosarApplication.GetInstance().ComponentDefinitionNameFont, defName);
        }


        public override void LoadFromXML(XElement xml)
        {
            base.LoadFromXML(xml);
            RunableInstances.LoadFromXML(xml);
            PerInstanceMemories.LoadFromXML(xml);
            CDataInstances.LoadFromXML(xml);
            String compDefString = XmlUtilits.GetFieldValue(xml, "ComponentDefenitionGuid", Guid.Empty.ToString());
            ComponentDefenitionGuid = GuidUtils.GetGuid(compDefString, false);
        }


        public override void WriteToXML(XElement root)
        {
            XElement xmlElement = new XElement("ComponentInstance");
            base.WriteToXML(xmlElement);  
            RunableInstances.WriteToXML(xmlElement);
            PerInstanceMemories.WriteToXML(xmlElement);
            CDataInstances.WriteToXML(xmlElement);
            XElement comptDefenitionGuid = new XElement("ComponentDefenitionGuid", ComponentDefenitionGuid.ToString());
            xmlElement.Add(comptDefenitionGuid);

            root.Add(xmlElement);
        }

        public void UpdatePims()
        {
            /* Delete unexists */
            for (int i = PerInstanceMemories.Count - 1; i >= 0; i--)
            {
                PimInstance pimInstance = PerInstanceMemories[i];
                if (ComponentDefenition.PerInstanceMemoryList.FindObject(pimInstance.DefenitionGuid) == null)
                {
                    PerInstanceMemories.RemoveAt(i);
                }
            }


            /* Adding */
            foreach (PimDefenition pimDef in ComponentDefenition.PerInstanceMemoryList)
            {
                if (PerInstanceMemories.GetPim(pimDef) == null)
                {
                    PimInstance pimInstace = PimFabric.GetInstance().CreatePimInstance(pimDef);
                    PerInstanceMemories.Add(pimInstace);
                }
            }

            /* Refresh default values */
            foreach (PimInstance pim in PerInstanceMemories)
            {
                pim.UpdateDefaultValues();
            }
        }

        public void UpdatePimNames()
        {
            for (int i = PerInstanceMemories.Count - 1; i >= 0; i--)
            {
                PimInstance pimInstance = PerInstanceMemories[i];
                pimInstance.Name = pimInstance.Defenition.Name;
                pimInstance.SyncronizeName();
            }
        }

        public void UpdateCDataNames()
        {
            for (int i = CDataInstances.Count - 1; i >= 0; i--)
            {
                CDataInstance instance = CDataInstances[i];
                instance.Name = instance.Defenition.Name;
                instance.SyncronizeName();
            }
        }

        public void UpdateCData()
        {
            /* Delete unexists */
            for (int i = CDataInstances.Count - 1; i >= 0; i--)
            {
                CDataInstance instance = CDataInstances[i];
                if (ComponentDefenition.CDataDefenitions.FindObject(instance.DefenitionGuid) == null)
                {
                    CDataInstances.RemoveAt(i);
                }
            }


            /* Adding */
            foreach (CDataDefenition def in ComponentDefenition.CDataDefenitions)
            {
                if (CDataInstances.GetCData(def) == null)
                {
                    CDataInstance instance = CDataFabric.GetInstance().CreateCDataInstance(def);
                    CDataInstances.Add(instance);
                }
            }

            /* Refresh default values */
            foreach (CDataInstance instance in CDataInstances)
            {
                instance.UpdateDefaultValues();
            }
        }

        public void SyncronizeRunnablesWithDefenition()
        {
            /* Delete non existing */
            for (int i = RunableInstances.Count - 1; i >= 0; i-- )
            {
                if (ComponentDefenition.Runnables.FindObject(RunableInstances[i].DefenitionGuid) == null)
                {
                    RunableInstances.RemoveAt(i);
                }
            }

            /* Add new */
            foreach (PeriodicRunnableDefenition runnableDefenition in ComponentDefenition.Runnables)
            {
                if (this.RunableInstances.FindRunnable(runnableDefenition.GUID) == null)
                {
                    /* Create new runnable instance */
                    PeriodicRunnableInstance newRunableInstance = ComponentFabric.GetInstance().CreateRunnableInstance(runnableDefenition);
                    this.RunableInstances.Add(newRunableInstance);
                }
            }
        }
    }
}
