///////////////////////////////////////////////////////////
//  PortType.cs
//  Implementation of the Enumeration PortType
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:08
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace AutosarGuiEditor.Source.PortDefenitions
{
	public enum PortType : int 
    {
		Sender,
		Receiver,
		Client,
		Server,
        Unknown
	}
}