///////////////////////////////////////////////////////////
//  PortConnectionPainter.cs
//  Implementation of the Class PortConnectionPainter
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:10
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using System.Windows.Media;
using AutosarGuiEditor.Source.Utility;
using System.Windows.Shapes;
using System.Windows;
using AutosarGuiEditor.Source.Render;
using AutosarGuiEditor.Source.SystemInterfaces;
using AutosarGuiEditor.Source.Painters.PortsPainters;
using AutosarGuiEditor.Source.Painters;
using AutosarGuiEditor.Source.Painters.Boundaries;
using AutosarGuiEditor.Source.Interfaces;

namespace System 
{
    public class PortConnection : IGUID, IRender, IClickable, ISelectable, IBoundary
    {
        private LineRendererList lines = new LineRendererList();

        public Guid PortPainter1Guid;
        public Guid PortPainter2Guid;

        AnchorList anchors = new AnchorList();

        public double LineWidth;
        public Color LineColor = Colors.Black;

		public PortConnection()
        {
            Visible = true;
		}

        public Boolean Visible
        {
            set;
            get;
        }

		public void Render(RenderContext context)
        {
            if (!PortPainter2Guid.Equals(Guid.Empty))
            {
                Point startPoint = Port1.GetConnectionPoint();
                Point endPoint = Port2.GetConnectionPoint();

                if (IsSelected())
                {
                    lines.LinesColor = Colors.Red;
                }
                else
                {
                    lines.LinesColor = Colors.Black;
                }

                lines.Render(context);

                if (IsSelected())
                {
                    RectanglePainter rectangle = new RectanglePainter();
                    rectangle.Width = 10;
                    rectangle.Height = 10;
                    rectangle.Left = startPoint.X - rectangle.Width / 2;
                    rectangle.Top  = startPoint.Y - rectangle.Height / 2;
                    rectangle.BackgroundColor = Colors.Blue;
                    rectangle.Render(context);

                    rectangle.Width = 10;
                    rectangle.Height = 10;
                    rectangle.Left = endPoint.X - rectangle.Width / 2;
                    rectangle.Top = endPoint.Y - rectangle.Height / 2;
                    rectangle.BackgroundColor = Colors.Blue;
                    rectangle.Render(context);
                    foreach (AnchorPoint point in anchors)
                    {
                        point.Render(context);
                    }
                }
            }
            else
            {
                Point startPoint = Port1.GetConnectionPoint();
                Point endPoint = SecondPoint;

                context.DrawLine(startPoint.X, startPoint.Y, endPoint.X, endPoint.Y, LineColor);
            }
		}

        public Boundary GetBoundary(RenderContext context)
        {
            Boundary boundary = new Boundary();
            if (lines.Count != 0)
            {
                double minX, maxX, minY, maxY;
                minX = Math.Min(lines[0].StartPoint.X, lines[0].EndPoint.X);
                maxX = Math.Max(lines[0].StartPoint.X, lines[0].EndPoint.X);
                minY = Math.Min(lines[0].StartPoint.Y, lines[0].EndPoint.Y);
                maxY = Math.Max(lines[0].StartPoint.Y, lines[0].EndPoint.Y);

                for (int i = 1; i < lines.Count; i++)
                {
                    double lminX = Math.Min(lines[i].StartPoint.X, lines[i].EndPoint.X);
                    double lmaxX = Math.Max(lines[i].StartPoint.X, lines[i].EndPoint.X);
                    double lminY = Math.Min(lines[i].StartPoint.Y, lines[i].EndPoint.Y);
                    double lmaxY = Math.Max(lines[i].StartPoint.Y, lines[i].EndPoint.Y);

                    minX = Math.Min(minX, lminX);
                    maxX = Math.Max(maxX, lmaxX);
                    minY = Math.Min(minY, lminY);
                    maxY = Math.Max(maxY, lmaxY);
                }

                boundary.Left = minX;
                boundary.Right = maxX;
                boundary.Top = minY;
                boundary.Bottom = maxY;
            }

            return boundary;
        }

        public PortPainter Port1
        {
            get
            {
                return AutosarApplication.GetInstance().FindPort(PortPainter1Guid);
            }
            set
            {
                UpdateName();
                PortPainter1Guid = value.GUID;
            }
        }

        public PortPainter Port2
        {
            get
            {
                return AutosarApplication.GetInstance().FindPort(PortPainter2Guid);
            }
            set
            {
                PortPainter2Guid = value.GUID;
                UpdateName();
            }
        }

        public void UpdateName()
        {
            String name = "NoName";
            if (Port1 != null)
            {
                name = AutosarApplication.GetInstance().FindComponentInstanceByPort(Port1).Name + "_" + Port1.PortDefenition.Name;
            }
            if (Port2 != null)
            {
                name += "_" + AutosarApplication.GetInstance().FindComponentInstanceByPort(Port2).Name + "_" + Port2.PortDefenition.Name;
            }
            this.Name = name;
        }

        public IElementWithPorts Component1
        {
            get
            {
                return AutosarApplication.GetInstance().FindComponentInstanceByPortGuid(PortPainter1Guid);
            }
        }

        public IElementWithPorts Component2
        {
            get
            {
                return AutosarApplication.GetInstance().FindComponentInstanceByPortGuid(PortPainter2Guid);
            }
        }

       

        public bool IsClicked(Point point, out Object clickedObject)
        {
            return IsClicked(point, out clickedObject, false);
        }

        public bool IsClicked(Point point, out Object clickedObject, Boolean checkAnchors)
        {
            clickedObject = null;

            if (!Visible)
            {
                return false;
            }

            Point startPoint = Port1.GetConnectionPoint();
            Point endPoint = Port2.GetConnectionPoint();

            if (checkAnchors)
            {
                foreach (AnchorPoint anchor in anchors)
                {
                    if (anchor.IsClicked(point, out clickedObject))
                    {
                        Select();
                        return true;
                    }
                }
            }
            else
            {
                if (lines.IsClicked(point, out clickedObject))
                {
                    clickedObject = this;
                    Select();
                    return true;
                }
            }
            return false;
        }

        public Point SecondPoint;

        bool selected = false;

        public void Unselect()
        {
            selected = false;
        }

        public bool IsSelected()
        {
            return selected;
        }

        public void Select()
        {
            selected = true;
        }

        public PortPainter GetOppositePort(PortPainter port)
        {
            if (port == Port1)
            {
                return Port2;
            }
            else
            {
                return Port1;
            }
        }
        
        public void AddPoint(Point newPoint)
        {
            if ((Port1 == null) || (Port2 == null))
            {
                return;
            }

            Point startPoint = Port1.GetConnectionPoint();
            Point endPoint = Port2.GetConnectionPoint();

            RectangleSide port1Side = Port1.ConnectionPortLocation;
            RectangleSide port2Side = Port2.ConnectionPortLocation;

            if (anchors.Count == 0)
            {
                // Оба горизонтально
                if ((port1Side == RectangleSide.Left || port1Side == RectangleSide.Right) &&
                    (port2Side == RectangleSide.Left || port2Side == RectangleSide.Right))
                {
                    double x1 = startPoint.X + 1.0 * (endPoint.X - startPoint.X) / 4.0;
                    double x2 = startPoint.X + 2.0 * (endPoint.X - startPoint.X) / 4.0;
                    double x3 = startPoint.X + 3.0 * (endPoint.X - startPoint.X) / 4.0;
                    double y2 = (startPoint.Y + endPoint.Y) / 2.0;

                    AnchorPoint point1 = new AnchorPoint(this);
                    point1.Position.X = x1;
                    point1.Position.Y = startPoint.Y;
                    point1.OnMove += Anchor_OnMove;
                    point1.Index = 0;
                    anchors.Add(point1);

                    AnchorPoint point2 = new AnchorPoint(this);
                    point2.Position.X = x2;
                    point2.Position.Y = y2;
                    point2.OnMove += Anchor_OnMove;
                    point2.Index = 1;
                    anchors.Add(point2);

                    AnchorPoint point3 = new AnchorPoint(this);
                    point3.Position.X = x3;
                    point3.Position.Y = endPoint.Y;
                    point3.OnMove += Anchor_OnMove;
                    point3.Index = 2;
                    anchors.Add(point3);

                    RecreateLines();
                }
                // Оба вертикально
                else if ((port1Side == RectangleSide.Top || port1Side == RectangleSide.Bottom) &&
                    (port2Side == RectangleSide.Top || port2Side == RectangleSide.Bottom))
                {
                    double y1 = startPoint.Y + 1.0 * (endPoint.Y - startPoint.Y) / 4.0;
                    double y2 = startPoint.Y + 2.0 * (endPoint.Y - startPoint.Y) / 4.0;
                    double y3 = startPoint.Y + 3.0 * (endPoint.Y - startPoint.Y) / 4.0;
                    double x2 = (startPoint.X + endPoint.X) / 2.0;

                    AnchorPoint point1 = new AnchorPoint(this);
                    point1.Position.X = startPoint.X;
                    point1.Position.Y = y1;
                    point1.OnMove += Anchor_OnMove;
                    point1.Index = 0;
                    anchors.Add(point1);

                    AnchorPoint point2 = new AnchorPoint(this);
                    point2.Position.X = x2;
                    point2.Position.Y = y2;
                    point2.OnMove += Anchor_OnMove;
                    point2.Index = 1;
                    anchors.Add(point2);

                    AnchorPoint point3 = new AnchorPoint(this);
                    point3.Position.X = endPoint.X;
                    point3.Position.Y = y3;
                    point3.OnMove += Anchor_OnMove;
                    point3.Index = 2;
                    anchors.Add(point3);

                    RecreateLines();
                }
                // Порты смотрят в разные стороны
                else 
                {
                    if (port1Side == RectangleSide.Top || port1Side == RectangleSide.Bottom)
                    {
                        Point midPoint = startPoint;
                        startPoint = endPoint;
                        endPoint = midPoint;
                    }

                    double x1 = (endPoint.X + startPoint.X) / 2.0;
                    double y2 = (endPoint.Y + startPoint.Y) / 2.0;

                    AnchorPoint point1 = new AnchorPoint(this);
                    point1.Position.X = x1;
                    point1.Position.Y = startPoint.Y;
                    point1.OnMove += Anchor_OnMove;
                    point1.Index = 0;
                    anchors.Add(point1);

                    AnchorPoint point2 = new AnchorPoint(this);
                    point2.Position.X = endPoint.X;
                    point2.Position.Y = y2;
                    point2.OnMove += Anchor_OnMove;
                    point2.Index = 1;
                    anchors.Add(point2);

                    RecreateLines();
                }
            }
        }

        public Boolean RecreateLines()
        {
            lines.Clear();
            if ((Port1 == null) || (Port2 == null))
            {
                return false;
            }
            Point startPoint = Port1.GetConnectionPoint();
            Point endPoint = Port2.GetConnectionPoint();

            if (anchors.Count == 0)
            {
                LineRenderer line = new LineRenderer();
                line.StartPoint = startPoint;
                line.EndPoint = endPoint;
                lines.Add(line);
            }
            else
            {
                RectangleSide port1Side = Port1.ConnectionPortLocation;
                RectangleSide port2Side = Port2.ConnectionPortLocation;

                if (port1Side == RectangleSide.Left || port1Side == RectangleSide.Right)
                {
                    lines.AddNewLine(startPoint.X, startPoint.Y, anchors[0].Position.X, startPoint.Y, LineColor);
                    startPoint.X = anchors[0].Position.X;

                    for (int i = 0; i < anchors.Count; i++)
                    {
                        if (i % 2 == 1)
                        {
                            lines.AddNewLine(startPoint.X, startPoint.Y, anchors[i].Position.X, startPoint.Y, LineColor);
                            startPoint.X = anchors[i].Position.X;
                        }
                        else
                        {
                            lines.AddNewLine(startPoint.X, startPoint.Y, startPoint.X, anchors[i].Position.Y, LineColor);
                            startPoint.Y = anchors[i].Position.Y;
                        }
                    }

                    if (port1Side == RectangleSide.Left || port1Side == RectangleSide.Right)
                    {
                        lines.AddNewLine(startPoint.X, startPoint.Y, startPoint.X, endPoint.Y, LineColor);
                        startPoint.Y = endPoint.Y;
                    }
                    lines.AddNewLine(startPoint, endPoint, LineColor);
                }

                
            }

            if (IsSelected())
            {
                lines.LinesColor = Colors.Black;
                lines.LinesColor = Colors.Red;
            }

            return true;
        }

        Boolean linesCreated = false;

        /* */
        public void UpdateLines()
        {
            RecreateLines();
            //if (linesCreated == false)
            //{
            //    linesCreated = RecreateLines();    
            //    if (linesCreated == false)
            //    {
            //        return;
            //    }
            //}
            //Point startPoint = Port1.GetConnectionPoint();
            //Point endPoint = Port2.GetConnectionPoint();
            //if (anchors.Count == 0)
            //{
            //    lines[0].UpdateCoordinates(startPoint, endPoint);                
            //}
            //else
            //{
            //    lines[0].UpdateCoordinates(startPoint.X, startPoint.Y, anchors[0].Position.X, startPoint.Y);
            //    lines[1].UpdateCoordinates(anchors[0].Position.X, startPoint.Y, anchors[0].Position.X, anchors[0].Position.Y);
            //
            //    int lineindex = 1;
            //    for (int i = 1; i < anchors.Count; i++)
            //    {
            //        lines[i + 1].UpdateCoordinates(anchors[i - 1].Position.X, anchors[i - 1].Position.Y, anchors[i].Position.X, anchors[i - 1].Position.Y);
            //        lines[i + 2].UpdateCoordinates(anchors[i].Position.X, anchors[i - 1].Position.Y, anchors[i].Position.X, anchors[i].Position.Y);
            //        lineindex += 2;
            //    }
            //
            //    lines[lineindex + 1].UpdateCoordinates(anchors[anchors.Count - 1].Position.X, anchors[anchors.Count - 1].Position.Y, anchors[anchors.Count - 1].Position.X, endPoint.Y);
            //    lines[lineindex + 2].UpdateCoordinates(anchors[anchors.Count - 1].Position.X, endPoint.Y, endPoint.X, endPoint.Y);
            //}
        }

        void Anchor_OnMove(object sender, Point translate)
        {
            UpdateLines();
        }

        public void RemoveAllAnchors()
        {
            if (anchors.Count == 0)
            {
                return;
            }

            anchors.Clear();

            RecreateLines();
        }

        public void DeleteAnchor(Point closestPoint)
        {
            if (anchors.Count == 0)
            {
                return;
            }
            
            AnchorPoint closestAnchor = anchors[0];
            double minDistance = MathUtility.Distance(closestAnchor.Position, closestPoint);

            for (int i = 1; i < anchors.Count; i++ )
            {
                double currDistance = MathUtility.Distance(anchors[i].Position, closestPoint);
                if (currDistance < minDistance)
                {
                    closestAnchor = anchors[i];
                    minDistance = currDistance;
                }
            }

            anchors.Remove(closestAnchor);

            UpdateLines();
        }

        public override void WriteToXML(XElement root)
        {
            XElement xmlElement = new XElement("Connection");
            base.WriteToXML(xmlElement);
            xmlElement.Add(new XElement("PortPainter1Guid", PortPainter1Guid.ToString("B")));
            xmlElement.Add(new XElement("PortPainter2Guid", PortPainter2Guid.ToString("B")));
            xmlElement.Add(new XElement("Visible", Visible.ToString()));
            anchors.WriteToXML(xmlElement);
            root.Add(xmlElement);
        }

        public void UpdateAnchorsOnMove()
        {
            foreach (AnchorPoint anchor in anchors)
            {
                anchor.OnMove += Anchor_OnMove;
            }
        }

        public override void LoadFromXML(XElement xml)
        {
            base.LoadFromXML(xml);

            String Component1Str = XmlUtilits.GetFieldValue(xml, "PortPainter1Guid", "");
            PortPainter1Guid = GuidUtils.GetGuid(Component1Str, false);

            String Component2Str = XmlUtilits.GetFieldValue(xml, "PortPainter2Guid", "");
            PortPainter2Guid = GuidUtils.GetGuid(Component2Str, false);

            String visible = XmlUtilits.GetFieldValue(xml, "Visible", "true");
            Visible = Convert.ToBoolean(visible);

            anchors.LoadFromXML(xml, this);
            RecreateLines();
        }
	}
}