///////////////////////////////////////////////////////////
//  PortConnectionPainter.cs
//  Implementation of the Class PortConnectionPainter
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:10
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using System.Windows.Media;
using AutosarGuiEditor.Source.Utility;
using System.Windows.Shapes;
using System.Windows;
using AutosarGuiEditor.Source.Render;
using AutosarGuiEditor.Source.SystemInterfaces;
using AutosarGuiEditor.Source.Painters.PortsPainters;
using AutosarGuiEditor.Source.Painters;
using AutosarGuiEditor.Source.Painters.Boundaries;
using AutosarGuiEditor.Source.Interfaces;

namespace System
{
    public class PortConnection : IGUID, IRender, IClickable, ISelectable, IBoundary
    {
        private LineRendererList lines = new LineRendererList();

        public Guid PortPainter1Guid;
        public Guid PortPainter2Guid;

        AnchorList anchors = new AnchorList();

        public double LineWidth;
        public Color LineColor = Colors.Black;

		public PortConnection()
        {
            Visible = true;
		}

        public Boolean Visible
        {
            set;
            get;
        }

		public void Render(RenderContext context)
        {
            if (!PortPainter2Guid.Equals(Guid.Empty))
            {
                Point startPoint = Port1.GetConnectionPoint();
                Point endPoint = Port2.GetConnectionPoint();

                if (IsSelected())
                {
                    lines.LinesColor = Colors.Red;
                }
                else
                {
                    lines.LinesColor = Colors.Black;
                }

                lines.Render(context);

                if (IsSelected())
                {
                    RectanglePainter rectangle = new RectanglePainter();
                    rectangle.Width = 10;
                    rectangle.Height = 10;
                    rectangle.Left = startPoint.X - rectangle.Width / 2;
                    rectangle.Top  = startPoint.Y - rectangle.Height / 2;
                    rectangle.BackgroundColor = Colors.Blue;
                    rectangle.Render(context);

                    rectangle.Width = 10;
                    rectangle.Height = 10;
                    rectangle.Left = endPoint.X - rectangle.Width / 2;
                    rectangle.Top = endPoint.Y - rectangle.Height / 2;
                    rectangle.BackgroundColor = Colors.Blue;
                    rectangle.Render(context);
                    foreach (AnchorPoint point in anchors)
                    {
                        point.Render(context);
                    }
                }
            }
            else
            {
                Point startPoint = Port1.GetConnectionPoint();
                Point endPoint = SecondPoint;

                context.DrawLine(startPoint.X, startPoint.Y, endPoint.X, endPoint.Y, LineColor);
            }
		}

        public Boundary GetBoundary(RenderContext context)
        {
            Boundary boundary = new Boundary();
            if (lines.Count != 0)
            {
                double minX, maxX, minY, maxY;
                minX = Math.Min(lines[0].StartPoint.X, lines[0].EndPoint.X);
                maxX = Math.Max(lines[0].StartPoint.X, lines[0].EndPoint.X);
                minY = Math.Min(lines[0].StartPoint.Y, lines[0].EndPoint.Y);
                maxY = Math.Max(lines[0].StartPoint.Y, lines[0].EndPoint.Y);

                for (int i = 1; i < lines.Count; i++)
                {
                    double lminX = Math.Min(lines[i].StartPoint.X, lines[i].EndPoint.X);
                    double lmaxX = Math.Max(lines[i].StartPoint.X, lines[i].EndPoint.X);
                    double lminY = Math.Min(lines[i].StartPoint.Y, lines[i].EndPoint.Y);
                    double lmaxY = Math.Max(lines[i].StartPoint.Y, lines[i].EndPoint.Y);

                    minX = Math.Min(minX, lminX);
                    maxX = Math.Max(maxX, lmaxX);
                    minY = Math.Min(minY, lminY);
                    maxY = Math.Max(maxY, lmaxY);
                }

                boundary.Left = minX;
                boundary.Right = maxX;
                boundary.Top = minY;
                boundary.Bottom = maxY;
            }

            return boundary;
        }

        public PortPainter Port1
        {
            get
            {
                return AutosarApplication.GetInstance().FindPort(PortPainter1Guid);
            }
            set
            {
                UpdateName();
                PortPainter1Guid = value.GUID;
            }
        }

        public PortPainter Port2
        {
            get
            {
                return AutosarApplication.GetInstance().FindPort(PortPainter2Guid);
            }
            set
            {
                PortPainter2Guid = value.GUID;
                UpdateName();
            }
        }

        public void UpdateName()
        {
            String name = "NoName";
            if (Port1 != null)
            {
                name = AutosarApplication.GetInstance().FindComponentInstanceByPort(Port1).Name + "_" + Port1.PortDefenition.Name;
            }
            if (Port2 != null)
            {
                name += "_" + AutosarApplication.GetInstance().FindComponentInstanceByPort(Port2).Name + "_" + Port2.PortDefenition.Name;
            }
            this.Name = name;
        }

        public IElementWithPorts Component1
        {
            get
            {
                return AutosarApplication.GetInstance().FindComponentInstanceByPortGuid(PortPainter1Guid);
            }
        }

        public IElementWithPorts Component2
        {
            get
            {
                return AutosarApplication.GetInstance().FindComponentInstanceByPortGuid(PortPainter2Guid);
            }
        }



        public bool IsClicked(Point point, out Object clickedObject)
        {
            return IsClicked(point, out clickedObject, false);
        }

        public bool IsClicked(Point point, out Object clickedObject, Boolean checkAnchors)
        {
            clickedObject = null;

            if (!Visible)
            {
                return false;
            }

            Point startPoint = Port1.GetConnectionPoint();
            Point endPoint = Port2.GetConnectionPoint();

            if (checkAnchors)
            {
                foreach (AnchorPoint anchor in anchors)
                {
                    if (anchor.IsClicked(point, out clickedObject))
                    {
                        Select();
                        return true;
                    }
                }
            }
            else
            {
                if (lines.IsClicked(point, out clickedObject))
                {
                    clickedObject = this;
                    Select();
                    return true;
                }
            }
            return false;
        }

        public Point SecondPoint;

        bool selected = false;

        public void Unselect()
        {
            selected = false;
        }

        public bool IsSelected()
        {
            return selected;
        }

        public void Select()
        {
            selected = true;
        }

        public PortPainter GetOppositePort(PortPainter port)
        {
            if (port == Port1)
            {
                return Port2;
            }
            else
            {
                return Port1;
            }
        }

        public void MakeOrthogonal(Point newPoint)
        {
            if ((Port1 == null) || (Port2 == null))
            {
                return;
            }

            if (anchors.Count != 0)
            {
                return;
            }

            Point startPoint = Port1.GetConnectionPoint();
            Point endPoint = Port2.GetConnectionPoint();

            RectangleSide port1Side = Port1.ConnectionPortLocation;
            RectangleSide port2Side = Port2.ConnectionPortLocation;


            // Оба горизонтально
            if ((port1Side == RectangleSide.Left || port1Side == RectangleSide.Right) &&
                (port2Side == RectangleSide.Left || port2Side == RectangleSide.Right))
            {
                double x1 = startPoint.X + 1.0 * (endPoint.X - startPoint.X) / 4.0;
                double x2 = startPoint.X + 2.0 * (endPoint.X - startPoint.X) / 4.0;
                double x3 = startPoint.X + 3.0 * (endPoint.X - startPoint.X) / 4.0;
                double y2 = (startPoint.Y + endPoint.Y) / 2.0;

                AnchorPoint point1 = new AnchorPoint(this);
                point1.Position.X = x1;
                point1.Position.Y = startPoint.Y;
                point1.OnMove += Anchor_OnMove;
                point1.OnMoveFinished += TryMergeAnchors;
                point1.Index = 0;
                point1.AllowedDirections = new HashSet<Direction> { Direction.Y };
                anchors.Add(point1);

                AnchorPoint point2 = new AnchorPoint(this);
                point2.Position.X = x2;
                point2.Position.Y = y2;
                point2.OnMove += Anchor_OnMove;
                point2.OnMoveFinished += TryMergeAnchors;
                point2.Index = 1;
                point2.AllowedDirections = new HashSet<Direction> { Direction.X };
                anchors.Add(point2);

                AnchorPoint point3 = new AnchorPoint(this);
                point3.Position.X = x3;
                point3.Position.Y = endPoint.Y;
                point3.OnMove += Anchor_OnMove;
                point3.OnMoveFinished += TryMergeAnchors;
                point3.Index = 2;
                point3.AllowedDirections = new HashSet<Direction> { Direction.Y };
                anchors.Add(point3);

                RecreateLines();
            }
            // Оба вертикально
            else if ((port1Side == RectangleSide.Top || port1Side == RectangleSide.Bottom) &&
                (port2Side == RectangleSide.Top || port2Side == RectangleSide.Bottom))
            {
                double y1 = startPoint.Y + 1.0 * (endPoint.Y - startPoint.Y) / 4.0;
                double y2 = startPoint.Y + 2.0 * (endPoint.Y - startPoint.Y) / 4.0;
                double y3 = startPoint.Y + 3.0 * (endPoint.Y - startPoint.Y) / 4.0;
                double x2 = (startPoint.X + endPoint.X) / 2.0;

                AnchorPoint point1 = new AnchorPoint(this);
                point1.Position.X = startPoint.X;
                point1.Position.Y = y1;
                point1.OnMove += Anchor_OnMove;
                point1.OnMoveFinished += TryMergeAnchors;
                point1.Index = 0;
                point1.AllowedDirections = new HashSet<Direction> { Direction.X };
                anchors.Add(point1);

                AnchorPoint point2 = new AnchorPoint(this);
                point2.Position.X = x2;
                point2.Position.Y = y2;
                point2.OnMove += Anchor_OnMove;
                point2.OnMoveFinished += TryMergeAnchors;
                point2.Index = 1;
                point2.AllowedDirections = new HashSet<Direction> { Direction.Y };
                anchors.Add(point2);

                AnchorPoint point3 = new AnchorPoint(this);
                point3.Position.X = endPoint.X;
                point3.Position.Y = y3;
                point3.OnMove += Anchor_OnMove;
                point3.OnMoveFinished += TryMergeAnchors;
                point3.Index = 2;
                point3.AllowedDirections = new HashSet<Direction> { Direction.X };
                anchors.Add(point3);

                RecreateLines();
            }
            // Порты смотрят в разные стороны
            else
            {
                var p1Directions = new HashSet<Direction>();
                var p2Directions = new HashSet<Direction>();

                if (port1Side == RectangleSide.Top || port1Side == RectangleSide.Bottom)
                {
                    Point midPoint = startPoint;
                    startPoint = endPoint;
                    endPoint = midPoint;

                    p1Directions = new HashSet<Direction> { Direction.X };
                    p2Directions = new HashSet<Direction> { Direction.Y };
                }
                else
                {
                    p1Directions = new HashSet<Direction> { Direction.Y };
                    p2Directions = new HashSet<Direction> { Direction.X };
                }

                double x1 = (endPoint.X + startPoint.X) / 2.0;
                double y2 = (endPoint.Y + startPoint.Y) / 2.0;

                AnchorPoint point1 = new AnchorPoint(this);
                point1.Position.X = x1;
                point1.Position.Y = startPoint.Y;
                point1.OnMove += Anchor_OnMove;
                point1.OnMoveFinished += TryMergeAnchors;
                point1.Index = 0;
                point1.AllowedDirections = p1Directions;
                anchors.Add(point1);

                AnchorPoint point2 = new AnchorPoint(this);
                point2.Position.X = endPoint.X;
                point2.Position.Y = y2;
                point2.OnMove += Anchor_OnMove;
                point2.OnMoveFinished += TryMergeAnchors;
                point2.Index = 1;
                point2.AllowedDirections = p1Directions;
                anchors.Add(point2);

                RecreateLines();
            }
        }

        public Boolean RecreateLines()
        {
            lines.Clear();
            if ((Port1 == null) || (Port2 == null))
            {
                return false;
            }

            Point startPoint = Port1.GetConnectionPoint();
            Point endPoint = Port2.GetConnectionPoint();

            if (anchors.Count == 0)
            {
                LineRenderer line = new LineRenderer();
                line.StartPoint = startPoint;
                line.EndPoint = endPoint;
                lines.Add(line);
            }
            else
            {
                RectangleSide port1Side = Port1.ConnectionPortLocation;
                RectangleSide port2Side = Port2.ConnectionPortLocation;

                for (int i = 0; i < anchors.Count - 1; i++)
                {
                    var anchor = anchors[i];
                    var nextAnchor = anchors[i + 1];

                    if (anchor.AllowedDirections.Contains(Direction.Y))
                    {
                        lines.AddNewLine(startPoint.X, startPoint.Y, nextAnchor.Position.X, startPoint.Y, LineColor);
                        startPoint.X = nextAnchor.Position.X;
                    }
                    else
                    {
                        lines.AddNewLine(startPoint.X, startPoint.Y, startPoint.X, nextAnchor.Position.Y, LineColor);
                        startPoint.Y = nextAnchor.Position.Y;
                    }
                }

                lines.AddNewLine(startPoint, endPoint, LineColor);
            }

            if (IsSelected())
            {
                lines.LinesColor = Colors.Black;
                lines.LinesColor = Colors.Red;
            }

            return true;
        }
        public void UpdateLines()
        {
            RecreateLines();
        }

        void Anchor_OnMove(object sender, Point translate)
        {
            var anchor = (sender as AnchorPoint);
            var connection = (anchor.GetOwner() as PortConnection);

            if (connection == null) { return; }

            if (connection.lines.Count <= 1)
            {
                return;
            }

            if (anchor.Index == 0)
            {
                var newDirection = new HashSet<Direction>();
                if (anchor.AllowedDirections.Contains(Direction.X))
                {
                    newDirection.Add(Direction.Y);
                }
                else
                {
                    newDirection.Add(Direction.X);
                }


                Point startPoint = Port1.GetConnectionPoint();
                
                AnchorPoint point1 = new AnchorPoint(this);
                if (anchor.AllowedDirections.Contains(Direction.X))
                {
                    point1.Position.X = (startPoint.X + anchor.Position.X) / 2;
                    point1.Position.Y = startPoint.Y;
                }
                else
                {
                    point1.Position.X = startPoint.X;
                    point1.Position.Y = (startPoint.Y + anchor.Position.Y) / 2;
                }
                point1.OnMove += Anchor_OnMove;
                point1.OnMoveFinished += TryMergeAnchors;
                point1.Index = 0;
                point1.AllowedDirections = newDirection;
                anchors.Insert(0, point1);

                RenumberAnchors();
            }
            else if (anchor.Index == connection.anchors.Count - 1)
            {
                var newDirection = new HashSet<Direction>();
                if (anchor.AllowedDirections.Contains(Direction.X))
                {
                    newDirection.Add(Direction.Y);
                }
                else
                {
                    newDirection.Add(Direction.X);
                }


                Point endPoint = Port2.GetConnectionPoint();

                AnchorPoint point1 = new AnchorPoint(this);
                if (anchor.AllowedDirections.Contains(Direction.X))
                {
                    point1.Position.X = (endPoint.X + anchor.Position.X) / 2;
                    point1.Position.Y = endPoint.Y;
                }
                else
                {
                    point1.Position.X = endPoint.X;
                    point1.Position.Y = (endPoint.Y + anchor.Position.Y) / 2;
                }
                point1.OnMove += Anchor_OnMove;
                point1.OnMoveFinished += TryMergeAnchors;
                point1.Index = 0;
                point1.AllowedDirections = newDirection;
                anchors.Add(point1);

                RenumberAnchors();
            }

            // Сдвигаем предыдущуй и следующий якоря
            List<int> indexesToMove = new List<int>();
            // Сдвигаем предыдущий
            if (anchor.Index != 0)
            {
                indexesToMove.Add(anchor.Index - 1);
            }
            // Сдвигаем следующий, если есть
            if (anchor.Index + 1 < connection.anchors.Count)
            {
                indexesToMove.Add(anchor.Index + 1);
            }

            for (int i = 0; i < indexesToMove.Count; i++)
            { 
                int indexToMove = indexesToMove[i]; 
                var shiftedAnchor = connection.anchors[indexToMove];
                //Если этой разрешено движение по X, то двигаем две предыдущие по Y
                if (anchor.AllowedDirections.Contains(Direction.X))
                {
                    shiftedAnchor.Position.X += translate.X / 2;
                }
                else
                {
                    shiftedAnchor.Position.Y += translate.Y / 2;
                }
            }


            UpdateLines();
        }

        private void RenumberAnchors()
        {
            for (int i = 0; i < anchors.Count; i++)
            {
                var anchor = anchors[i];
                anchor.Index = i;
            }
        }

        public void RemoveAllAnchors()
        {
            if (anchors.Count == 0)
            {
                return;
            }

            anchors.Clear();

            RecreateLines();
        }

        private void TryMergeAnchors(object sender)
        {
            if (anchors.Count <= 2)
            {
                return;
            }

            var startPoint = Port1.GetConnectionPoint();

            for (var i = 0; i < anchors.Count - 3; i++)
            {
                if (i > 0)
                {
                    if (anchors[i].AllowedDirections.Contains(Direction.X))
                    {
                        startPoint.X = anchors[i].Position.X;
                    }
                    else
                    {
                        startPoint.Y = anchors[i].Position.Y;
                    }
                }
                
                // Выбираем между конечным портом или якорем через два
                Point endPoint = i < anchors.Count - 3 ? anchors[i + 3].Position : Port2.GetConnectionPoint();
                
                var activeAnchor = anchors[i]; 
                double xDist = Math.Abs(activeAnchor.Position.X - anchors[i + 2].Position.X);
                double yDist = Math.Abs(activeAnchor.Position.Y - anchors[i + 2].Position.Y);

                if (anchors[i].AllowedDirections.Contains(Direction.Y))
                {
                    if (yDist < AnchorsStep.Step * 2)
                    {
                        anchors.RemoveAt(i + 2);
                        anchors.RemoveAt(i + 1);
                        activeAnchor.Position.X = (startPoint.X + endPoint.X) / 2;
                        RenumberAnchors();
                        i = 0;
                        startPoint = Port1.GetConnectionPoint();
                    }
                }
                else
                {
                    if (xDist < AnchorsStep.Step * 2)
                    {
                        anchors.RemoveAt(i + 2);
                        anchors.RemoveAt(i + 1);
                        activeAnchor.Position.Y = (startPoint.Y + endPoint.Y) / 2;
                        RenumberAnchors();
                        i = 0;
                        startPoint = Port1.GetConnectionPoint();
                    }
                }
                RecreateLines();
            }
        }

        public void DeleteAnchor(Point closestPoint)
        {
            if (anchors.Count == 0)
            {
                return;
            }

            AnchorPoint closestAnchor = anchors[0];
            double minDistance = MathUtility.Distance(closestAnchor.Position, closestPoint);

            for (int i = 1; i < anchors.Count; i++ )
            {
                double currDistance = MathUtility.Distance(anchors[i].Position, closestPoint);
                if (currDistance < minDistance)
                {
                    closestAnchor = anchors[i];
                    minDistance = currDistance;
                }
            }

            anchors.Remove(closestAnchor);

            UpdateLines();
        }

        public override void WriteToXML(XElement root)
        {
            XElement xmlElement = new XElement("Connection");
            base.WriteToXML(xmlElement);
            xmlElement.Add(new XElement("PortPainter1Guid", PortPainter1Guid.ToString("B")));
            xmlElement.Add(new XElement("PortPainter2Guid", PortPainter2Guid.ToString("B")));
            xmlElement.Add(new XElement("Visible", Visible.ToString()));
            anchors.WriteToXML(xmlElement);
            root.Add(xmlElement);
        }

        public void UpdateAnchorsOnMove()
        {
            foreach (AnchorPoint anchor in anchors)
            {
                anchor.OnMove += Anchor_OnMove;
                anchor.OnMoveFinished += TryMergeAnchors;
            }
        }

        public override void LoadFromXML(XElement xml)
        {
            base.LoadFromXML(xml);

            String Component1Str = XmlUtilits.GetFieldValue(xml, "PortPainter1Guid", "");
            PortPainter1Guid = GuidUtils.GetGuid(Component1Str, false);

            String Component2Str = XmlUtilits.GetFieldValue(xml, "PortPainter2Guid", "");
            PortPainter2Guid = GuidUtils.GetGuid(Component2Str, false);

            String visible = XmlUtilits.GetFieldValue(xml, "Visible", "true");
            Visible = Convert.ToBoolean(visible);

            anchors.LoadFromXML(xml, this);
            RecreateLines();
            UpdateAnchorsOnMove();
        }
	}
}