///////////////////////////////////////////////////////////
//  RectanglePainter.cs
//  Implementation of the Class RectanglePainter
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:10
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class RectanglePainter : Renderer {

		public Color BackgroundColor;
		public int Height;
		public int Left;
		public int Top;
		public int Width;

		public RectanglePainter(){

		}

		~RectanglePainter(){

		}

		/// 
		/// <param name="context"></param>
		public void Draw(RenderContext context){

		}

	}//end RectanglePainter

}//end namespace System