///////////////////////////////////////////////////////////
//  Renderer.cs
//  Implementation of the Class Renderer
//  Generated by Enterprise Architect
//  Created on:      26-мар-2019 7:30:47
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Renderer {

		private Renderer _parent;
		public Vector2D Position;

		public Renderer(){

		}

		~Renderer(){

		}

		/// 
		/// <param name="context"></param>
		public void Render(RenderContext context){

		}

	}//end Renderer

}//end namespace System