///////////////////////////////////////////////////////////
//  RenderContext.cs
//  Implementation of the Class RenderContext
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:09
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class RenderContext {

		public RenderContext(){

		}

		~RenderContext(){

		}

	}//end RenderContext

}//end namespace System