///////////////////////////////////////////////////////////
//  Scene.cs
//  Implementation of the Class Scene
//  Generated by Enterprise Architect
//  Created on:      26-мар-2019 7:30:39
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Scene {

		public List<Painter> Childrens;
		public ComponentPainterList ComponentsPainters;
		public PortsConnectionsPaintersList ConnectionsPainters;
		public float Scale;
		public float TranslateX;
		public float TranslateY;

		public Scene(){

		}

		~Scene(){

		}

		/// 
		/// <param name="bitmap"></param>
		public Scene(WritableBitmap bitmap){

		}

		/// 
		/// <param name="mouseCoord"></param>
		public Point MouseToXY(Point mouseCoord){

			return null;
		}

		/// 
		/// <param name="context"></param>
		public void Render(RenderContext context){

		}

		public void RenderScene(){

		}

		/// 
		/// <param name="xyCoord"></param>
		public Point XYtoImage(point xyCoord){

			return null;
		}

	}//end Scene

}//end namespace System