///////////////////////////////////////////////////////////
//  AnchorList.cs
//  Implementation of the Class AnchorList
//  Generated by Enterprise Architect
//  Created on:      30-мар-2019 9:34:39
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using AutosarGuiEditor.Source.Render;
using System.Windows;
using System.Xml.Linq;

namespace System {
	public class AnchorList : List<AnchorPoint> {

		public AnchorList(){

		}

		~AnchorList(){

		}

        public void RenderAnchors(RenderContext context)
        {
            foreach(AnchorPoint anchor in this)
            {
                anchor.Render(context);
            }
        }

        public bool IsClicked(Point point, out Object clickedObject)
        {
            foreach(AnchorPoint anchor in this)
            {
                bool clicked = anchor.IsClicked(point, out clickedObject);
                if (clicked)
                {
                    return true;
                }
            }
            clickedObject = false;
            return false;
        }

        const string XmlListName = "Anchors";

        public void WriteToXML(XElement root)
        {
            XElement dtList = new XElement(XmlListName);
            foreach (AnchorPoint point in this)
            {
                point.WriteToXML(dtList);
            }
            root.Add(dtList);
        }

        public void LoadFromXML(XElement xmlApp, object owner)
        {
            XElement xmlList = xmlApp.Element(XmlListName);
            IEnumerable<XElement> elementsList = xmlList.Elements();
            foreach (var element in elementsList)
            {
                AnchorPoint point = new AnchorPoint(owner);
                point.LoadFromXML(element);
                this.Add(point);
            }
        }

	}//end AnchorList

}//end namespace System