///////////////////////////////////////////////////////////
//  Renderer.cs
//  Implementation of the Class Renderer
//  Generated by Enterprise Architect
//  Created on:      26-мар-2019 7:30:47
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows;

namespace System 
{
	public interface IRender
    {
        void Render(RenderContext context);
	}
}