///////////////////////////////////////////////////////////
//  RenderContext.cs
//  Implementation of the Class RenderContext
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:09
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Media.Imaging;
using System.Windows;
using System.Windows.Media;



namespace System {

    public class ViewPort
    {
        public int Width;
        public int Height;
        
        public ViewPort(int width, int height)
        {
            writeableBmp = BitmapFactory.New(width, height);
        }

        WriteableBitmap writeableBmp;
        public WriteableBitmap WriteableBmp
        {
            get
            {
                return writeableBmp;
            }
        }

        public void Clear()
        {
            writeableBmp.Clear(Colors.White);
        }

        public void Resize(int width, int height)
        {
            writeableBmp = BitmapFactory.New(width, height);
        }
    }

	public class RenderContext {

        private WriteableBitmap bmp;
        public WriteableBitmap Bitmap
        {
            get
            {
                return bmp;
            }
        }

        public RenderContext(WriteableBitmap bitmap)
        {
            bmp = bitmap;
        }

        public Point Offset = new Point(0, 0);

        private const double MaxScale = 10;
        private const double MinScale = 0.2;
        public double scale = 1.0d;
        public double Scale
        {
            get
            {
                return scale;
            }
            set
            {
                /* Apply saturation */
                if (value > MaxScale)
                {
                    scale = MaxScale;
                }
                else if (value < MinScale)
                {
                    scale = MinScale;
                }
                else
                {
                    scale = value;
                }
            }
        }

		~RenderContext(){

		}

        public void Clear()
        {
            bmp.Clear(Colors.White);
        }

        public void DrawLine(double startX, double startY, double endX, double endY, Color color, double thickness)
        {
            startX = Offset.X + startX * Scale;
            startY = Offset.Y + startY * Scale;
            endX = Offset.X + endX * Scale;
            endY = Offset.Y + endY * Scale;
            int thick = (int)(thickness * Scale);
            if (thick < 1)
            {
                thick = 1;
            }
            bmp.DrawLineAa((int)startX, (int)startY, (int)endX, (int)endY, color, thick);
        }

        public void DrawLine(double startX, double startY, double endX, double endY, Color color)
        {
            startX = Offset.X + startX * Scale;
            startY = Offset.Y + startY * Scale;
            endX = Offset.X + endX * Scale;
            endY = Offset.Y + endY * Scale;
            bmp.DrawLine((int)startX, (int)startY, (int)endX, (int)endY, color);
        }

        int ShiftAndScaleX(double x)
        {
            int xPoint = (int)(Offset.X + x * Scale);
            return xPoint;
        }

        int ShiftAndScaleY(double y)
        {
            int yPoint = (int)(Offset.Y + y * Scale);
            return yPoint;
        }

        private void DrawArcSegment(int cx, int cy, double r, int count, ref double currentRad, double stepSize, ref int prevX, ref int prevY, Color color)
        {
            for (int i = 0; i < count; i++)
            {
                // Move to the next angle
                currentRad += stepSize;

                // Calculate new coordinates
                // Math.Cos returns X, Math.Sin returns Y
                // Note: We subtract Sin(Y) because standard math Y is up, screen Y is down.
                int currX = (int)(cx + r * Math.Cos(currentRad));
                int currY = (int)(cy - r * Math.Sin(currentRad));

                // Draw the line segment from previous point to current point
                DrawLine(prevX, prevY, currX, currY, color);

                // Update previous for next iteration
                prevX = currX;
                prevY = currY;
            }
        }

        public void DrawArc(Point center, double radius, double startAngleDeg, double endAngleDeg, Color color)
        {
            const int segments = 30;

            // Convert angles to radians (Math functions use Radians)
            double startRad = startAngleDeg * Math.PI / 180.0;
            double endRad = endAngleDeg * Math.PI / 180.0;

            // Calculate total span. 
            // Note: This implementation assumes end > start. 
            // If you need to handle wrapping (e.g., 350 to 20), logic is needed here.
            double angleSpan = endRad - startRad;

            if (Math.Abs(angleSpan) < 1e-9) return; // Nothing to draw

            // Create the array: 2 coordinates per point * (segments + 1 points)
            int[] points = new int[(segments + 1) * 2];

            double stepSize = angleSpan / segments;

            for (int i = 0; i <= segments; i++)
            {
                // Calculate current angle for this point
                double currentRad = startRad + (i * stepSize);

                // Calculate coordinates
                // X = center + r * cos(theta)
                // Y = center - r * sin(theta)  <-- Minus because screen Y goes down
                double x = center.X + radius * Math.Cos(currentRad);
                double y = center.Y - radius * Math.Sin(currentRad);

                // Store in array: [x0, y0, x1, y1, ...]
                points[i * 2] = (int)GetImageCoordinateX(x);
                points[i * 2 + 1] = (int)GetImageCoordinateY(y);
            }

            // Call the drawing function
            bmp.DrawPolyline(points, color);
        }

        public void DrawRectangle(double startX, double startY, double endX, double endY, Color color)
        {            
            startX = Offset.X + startX * Scale;
            startY = Offset.Y + startY * Scale;
            endX = Offset.X + endX * Scale;
            endY = Offset.Y + endY * Scale;
            bmp.DrawRectangle((int)startX, (int)startY, (int)endX, (int)endY, color);
        }

        public void DrawFillRectangle(double startX, double startY, double endX, double endY, Color color)
        {
            startX = Offset.X + startX * Scale;
            startY = Offset.Y + startY * Scale;
            endX = Offset.X + endX * Scale;
            endY = Offset.Y + endY * Scale;
            bmp.FillRectangle((int)startX, (int)startY, (int)endX, (int)endY, color);           
        }

        public void DrawEllipse(double startX, double startY, double endX, double endY, Color color)
        {
            startX = Offset.X + startX * Scale;
            startY = Offset.Y + startY * Scale;
            endX = Offset.X + endX * Scale;
            endY = Offset.Y + endY * Scale;
            bmp.DrawEllipse((int)startX, (int)startY, (int)endX, (int)endY, color);    
        }

        public void DrawEllipseCentered(double startX, double startY, double endX, double endY, Color color, int thickness)
        {
            int count = (int)(thickness * Scale);
            if (count < 1)
            {
                count = 1;
            }
            if (count == 1)
            {
                startX = Offset.X + startX * Scale;
                startY = Offset.Y + startY * Scale;
                endX = Offset.X + endX * Scale;
                endY = Offset.Y + endY * Scale;

                double cx = (startX + endX) / 2.0;
                double cy = (startY + endY) / 2.0;
                double xr = Math.Abs(startX - endX) / 2.0;
                double yr = Math.Abs(startY - endY) / 2.0;

                bmp.DrawEllipseCentered((int)cx, (int)cy, (int)xr, (int)yr, color);
            }
            else
            {
                if (count % 2 == 0)
                {
                    count++;
                }
                double step = thickness * Scale / count;
                double half = thickness * Scale / 2.0;

                startX = Offset.X + startX * Scale;
                startY = Offset.Y + startY * Scale;
                endX = Offset.X + endX * Scale;
                endY = Offset.Y + endY * Scale;

                int cx = (int)((startX + endX) / 2.0);
                int cy = (int)((startY + endY) / 2.0);
                int minRad = (int)(Math.Abs(startX - endX) / 2.0 - half);
                int maxRad = (int)(Math.Abs(startX - endX) / 2.0 + half);
                for (int i = minRad; i <= maxRad; i++)
                {
                     bmp.DrawEllipseCentered((int)cx, (int)cy, (int)i, (int)i, color);
                }
            }
        }

        public void DrawFillTriangle(double x1, double y1, double x2, double y2, double x3, double y3, Color color)
        {
            x1 = Offset.X + x1 * Scale;
            x2 = Offset.X + x2 * Scale;
            x3 = Offset.X + x3 * Scale;
            y1 = Offset.Y + y1 * Scale;
            y2 = Offset.Y + y2 * Scale;
            y3 = Offset.Y + y3 * Scale;

            bmp.FillTriangle((int)x1, (int)y1, (int)x2, (int)y2, (int)x3, (int)y3, color);
        }

        public double GetImageCoordinateX(double x)
        {
            double xWorld = Offset.X + x * Scale;
            return xWorld;
        }

        public double GetImageCoordinateY(double y)
        {
            double yWorld = Offset.Y + y * Scale;
            return yWorld;
        }

        public Point GetImageCoordinate(Point worldCoordinate)
        {
            Point imageCoord = new Point(0, 0);

            imageCoord.X = Offset.X + worldCoordinate.X * Scale;
            imageCoord.Y = Offset.Y + worldCoordinate.Y * Scale;

            return imageCoord;
        }

        public Point GetWorldCoordinate(Point imageCoordinate)
        {
            Point sceneCoord = new Point(0, 0);

            //CoordX = offset.X + RealCoord * scale 
            // =>
            // RealCoord = ( CoordX - offsetX ) / scale

            sceneCoord.X = (imageCoordinate.X - Offset.X) / Scale;
            sceneCoord.Y = (imageCoordinate.Y - Offset.Y) / Scale;

            return sceneCoord;
        }
	}//end RenderContext

}//end namespace System