//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosarGuiEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutosarGuiEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClientPort {
            get {
                object obj = ResourceManager.GetObject("ClientPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        internal static string COMPONENTS_FOLDER {
            get {
                return ResourceManager.GetString("COMPONENTS_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains all datatypes for programm architecture..
        /// </summary>
        internal static string DATATYPES_H_FILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("DATATYPES_H_FILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReceiverPort {
            get {
                object obj = ResourceManager.GetObject("ReceiverPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rte_Connections.c.
        /// </summary>
        internal static string RTE_CONNECTIONS_C_FILENAME {
            get {
                return ResourceManager.GetString("RTE_CONNECTIONS_C_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rte_DataTypes.h.
        /// </summary>
        internal static string RTE_DATATYPES_H_FILENAME {
            get {
                return ResourceManager.GetString("RTE_DATATYPES_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE_E_OK.
        /// </summary>
        internal static string RTE_E_OK {
            get {
                return ResourceManager.GetString("RTE_E_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE_E_UNCONNECTED.
        /// </summary>
        internal static string RTE_E_UNCONNECTED {
            get {
                return ResourceManager.GetString("RTE_E_UNCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file will keep all links to components runnables..
        /// </summary>
        internal static string RTE_EXTERNAL_RUNNABLES_FILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("RTE_EXTERNAL_RUNNABLES_FILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rte_ExternalRunnables.h.
        /// </summary>
        internal static string RTE_EXTERNAL_RUNNABLES_H_FILENAME {
            get {
                return ResourceManager.GetString("RTE_EXTERNAL_RUNNABLES_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE.
        /// </summary>
        internal static string RTE_FOLDER {
            get {
                return ResourceManager.GetString("RTE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rte_ReturnCodes.h.
        /// </summary>
        internal static string RTE_RETURN_CODES_FILENAME {
            get {
                return ResourceManager.GetString("RTE_RETURN_CODES_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunTimeEnvironment.c.
        /// </summary>
        internal static string RTE_RUNTIME_ENVIRONMENT_C_FILENAME {
            get {
                return ResourceManager.GetString("RTE_RUNTIME_ENVIRONMENT_C_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component run all tasks with their own period.
        /// </summary>
        internal static string RTE_RUNTIME_ENVIRONMENT_FILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("RTE_RUNTIME_ENVIRONMENT_FILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunTimeEnvironment.h.
        /// </summary>
        internal static string RTE_RUNTIME_ENVIRONMENT_H_FILENAME {
            get {
                return ResourceManager.GetString("RTE_RUNTIME_ENVIRONMENT_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains implementation for components runnables scheduler..
        /// </summary>
        internal static string RTE_SCHEDULER_C_FILE_DESCRIPTION {
            get {
                return ResourceManager.GetString("RTE_SCHEDULER_C_FILE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rte_Scheduler.c.
        /// </summary>
        internal static string RTE_SCHEDULER_C_FILENAME {
            get {
                return ResourceManager.GetString("RTE_SCHEDULER_C_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rte_Scheduler.h.
        /// </summary>
        internal static string RTE_SCHEDULER_H_FILENAME {
            get {
                return ResourceManager.GetString("RTE_SCHEDULER_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ServerPort {
            get {
                object obj = ResourceManager.GetObject("ServerPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std_ReturnType .
        /// </summary>
        internal static string STD_RETURN_TYPE {
            get {
                return ResourceManager.GetString("STD_RETURN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemErrors.h.
        /// </summary>
        internal static string SYSTEM_ERRORS_H_FILENAME {
            get {
                return ResourceManager.GetString("SYSTEM_ERRORS_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTICK_FREQUENCY.
        /// </summary>
        internal static string SYSTICK_FREQUENCY {
            get {
                return ResourceManager.GetString("SYSTICK_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uCUnit-v1.0.h.
        /// </summary>
        internal static string TEST_FRAMEWORK_H_FILENAME {
            get {
                return ResourceManager.GetString("TEST_FRAMEWORK_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestInitialization.c.
        /// </summary>
        internal static string TEST_INITIALIZATION_FILENAME {
            get {
                return ResourceManager.GetString("TEST_INITIALIZATION_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestRte.c.
        /// </summary>
        internal static string TEST_RTE_C_FILENAME {
            get {
                return ResourceManager.GetString("TEST_RTE_C_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestRte.h.
        /// </summary>
        internal static string TEST_RTE_H_FILENAME {
            get {
                return ResourceManager.GetString("TEST_RTE_H_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TransmitterPort {
            get {
                object obj = ResourceManager.GetObject("TransmitterPort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
