///////////////////////////////////////////////////////////
//  ComplexDataTypesList.cs
//  Implementation of the Class ComplexDataTypesList
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:12
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using AutosarGuiEditor.Source.Interfaces;
using AutosarGuiEditor.Source.DataTypes.ComplexDataType;



namespace System 
{
    public class ComplexDataTypesList : IGuidList<ComplexDataType>
    {
        public override String GetName()
        {
            return "Complex data types";
        }
	}
}