///////////////////////////////////////////////////////////
//  AddPortCommand.cs
//  Implementation of the Class AddPortCommand
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:11
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class AddPortCommand : ICommand {

		public AddPortCommand(){

		}

		~AddPortCommand(){

		}

	}//end AddPortCommand

}//end namespace System