///////////////////////////////////////////////////////////
//  CreateSimpleDataTypeCommand.cs
//  Implementation of the Class CreateSimpleDataTypeCommand
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:12
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class CreateSimpleDataTypeCommand : ICommand {

		public CreateSimpleDataTypeCommand(){

		}

		~CreateSimpleDataTypeCommand(){

		}

	}//end CreateSimpleDataTypeCommand

}//end namespace System