///////////////////////////////////////////////////////////
//  PaintWindowClicker.cs
//  Implementation of the Class PaintWindowClicker
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:10
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class PaintWindowClicker {

		public Object SelectedObject;

		public PaintWindowClicker(){

		}

		~PaintWindowClicker(){

		}

		public void PaintWindowClick(){

		}

	}//end PaintWindowClicker

}//end namespace System