///////////////////////////////////////////////////////////
//  Runnable.cs
//  Implementation of the Class Runnable
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:11
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using AutosarGuiEditor.Source.SystemInterfaces;


namespace AutosarGuiEditor.Source.Component 
{
	public class RunnableDefenition : IGUID 
    {
        public RunnableDefenition()
        {
            Name = "Refresh";
        }

        public RunnableDefenition(string name)
        {
            Name = name;
		}

        public override void LoadFromXML(XElement xml)
        {
            base.LoadFromXML(xml);
        }

        public override void WriteToXML(XElement root)
        {
            XElement xmlElement = new XElement("Runnable");
            base.WriteToXML(xmlElement);
            root.Add(xmlElement);
        }
	}
}