///////////////////////////////////////////////////////////
//  RunnableList.cs
//  Implementation of the Class RunnableList
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:11
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Linq;
using AutosarGuiEditor.Source.Interfaces;

namespace AutosarGuiEditor.Source.Component 
{
    public class RunnableDefenitionsList : IGuidList<PeriodicRunnableDefenition>
    {
        public RunnableDefenitionsList()
        {

        }

        public override String GetName()
        {
            return "Periodic runnable defenitions";
        }
	}
}