///////////////////////////////////////////////////////////
//  IClickable.cs
//  Implementation of the Interface IClickable
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:10
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows;

namespace System 
{
    public interface IClickable
    {
        bool IsClicked(Point point, out Object clickedObject);        
    }	
}