///////////////////////////////////////////////////////////
//  ICommand.cs
//  Implementation of the Interface ICommand
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:11
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public interface ICommand  {

	}//end ICommand

}//end namespace System