///////////////////////////////////////////////////////////
//  IDraw.cs
//  Implementation of the Interface IDraw
//  Generated by Enterprise Architect
//  Created on:      24-мар-2019 20:54:09
//  Original author: Ivan
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public interface IDraw  {

		/// 
		/// <param name="context"></param>
		void Draw(RenderContext context);
	}//end IDraw

}//end namespace System